//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UNIMEDIC.API.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_MedicalStaff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_MedicalStaff()
        {
            this.tbl_Admin = new HashSet<tbl_Admin>();
            this.tbl_Doctor = new HashSet<tbl_Doctor>();
            this.tbl_Login = new HashSet<tbl_Login>();
            this.tbl_Visit = new HashSet<tbl_Visit>();
            this.tbl_VitalSigns = new HashSet<tbl_VitalSigns>();
        }
    
        public int ItbId { get; set; }
        public int taskid { get; set; }
        public string Staff_code { get; set; }
        public string First_name { get; set; }
        public string Last_name { get; set; }
        public string Other_name { get; set; }
        public string Gender { get; set; }
        public string Position { get; set; }
        public string Phone_num { get; set; }
        public string Address { get; set; }
        public string Nationality { get; set; }
        public string Staff_type { get; set; }
        public string Role { get; set; }
        public string Status { get; set; }
        public string Createdby { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Admin> tbl_Admin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Doctor> tbl_Doctor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Login> tbl_Login { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Visit> tbl_Visit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_VitalSigns> tbl_VitalSigns { get; set; }
    }
}
