//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UNIMEDIC.API.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Visit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Visit()
        {
            this.tbl_Diagnosis = new HashSet<tbl_Diagnosis>();
            this.tbl_VitalSigns = new HashSet<tbl_VitalSigns>();
        }
    
        public int ItbId { get; set; }
        public int taskid { get; set; }
        public Nullable<System.DateTime> Visit_datetime { get; set; }
        public int Patient_id { get; set; }
        public int Recordstaff_id { get; set; }
        public int Clinic_id { get; set; }
        public string Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual tbl_Clinic tbl_Clinic { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Diagnosis> tbl_Diagnosis { get; set; }
        public virtual tbl_MedicalStaff tbl_MedicalStaff { get; set; }
        public virtual tbl_Patient tbl_Patient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_VitalSigns> tbl_VitalSigns { get; set; }
    }
}
