//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UNIMEDIC.API.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Login
    {
        public int ItbId { get; set; }
        public int taskid { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string User_type { get; set; }
        public int Medical_staff { get; set; }
        public int UserID { get; set; }
        public string status { get; set; }
        public string Createdby { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual tbl_Admin tbl_Admin { get; set; }
        public virtual tbl_MedicalStaff tbl_MedicalStaff { get; set; }
    }
}
