//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UNIMEDIC.API.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_NextOfKin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_NextOfKin()
        {
            this.tbl_Patient = new HashSet<tbl_Patient>();
        }
    
        public int ItbId { get; set; }
        public int taskid { get; set; }
        public string Last_name { get; set; }
        public string First_name { get; set; }
        public string Other_names { get; set; }
        public string Phone_number { get; set; }
        public string Gender { get; set; }
        public string Address { get; set; }
        public string Relationship { get; set; }
        public string Status { get; set; }
        public string Createdby { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Patient> tbl_Patient { get; set; }
    }
}
