//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UNIMEDIC.API.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Patient()
        {
            this.tbl_Emergency = new HashSet<tbl_Emergency>();
            this.tbl_Staff_Patient = new HashSet<tbl_Staff_Patient>();
            this.tbl_Student_Patient = new HashSet<tbl_Student_Patient>();
            this.tbl_Visit = new HashSet<tbl_Visit>();
        }
    
        public int ItbId { get; set; }
        public int taskid { get; set; }
        public string Last_name { get; set; }
        public string First_name { get; set; }
        public string Other_names { get; set; }
        public string Phone_number { get; set; }
        public string Gender { get; set; }
        public string Hospital_number { get; set; }
        public Nullable<System.DateTime> Date_of_birth { get; set; }
        public string Address { get; set; }
        public string Marital_status { get; set; }
        public string Nationality { get; set; }
        public string Patient_type { get; set; }
        public int Next_of_kin { get; set; }
        public int Department { get; set; }
        public Nullable<int> Dependent_id { get; set; }
        public string Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual tbl_Department tbl_Department { get; set; }
        public virtual tbl_Dependent tbl_Dependent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Emergency> tbl_Emergency { get; set; }
        public virtual tbl_NextOfKin tbl_NextOfKin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Staff_Patient> tbl_Staff_Patient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Student_Patient> tbl_Student_Patient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Visit> tbl_Visit { get; set; }
    }
}
