//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UNIMEDIC.API.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Staff_Patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Staff_Patient()
        {
            this.tbl_Dependent = new HashSet<tbl_Dependent>();
        }
    
        public int ItbId { get; set; }
        public int taskid { get; set; }
        public string Staff_code { get; set; }
        public Nullable<int> No_of_dependent { get; set; }
        public Nullable<int> Date_of_employment { get; set; }
        public int Patient_id { get; set; }
        public string Status { get; set; }
        public string Createdby { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Dependent> tbl_Dependent { get; set; }
        public virtual tbl_Patient tbl_Patient { get; set; }
    }
}
