//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UNIMEDIC.API.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class UNILAG_MCEntities : DbContext
    {
        public UNILAG_MCEntities()
            : base("name=UNILAG_MCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Admin> tbl_Admin { get; set; }
        public virtual DbSet<tbl_Clinic> tbl_Clinic { get; set; }
        public virtual DbSet<tbl_ClinicOpenSchedule> tbl_ClinicOpenSchedule { get; set; }
        public virtual DbSet<tbl_Department> tbl_Department { get; set; }
        public virtual DbSet<tbl_Dependent> tbl_Dependent { get; set; }
        public virtual DbSet<tbl_Diagnosis> tbl_Diagnosis { get; set; }
        public virtual DbSet<tbl_Doctor> tbl_Doctor { get; set; }
        public virtual DbSet<tbl_Emergency> tbl_Emergency { get; set; }
        public virtual DbSet<tbl_Faculty> tbl_Faculty { get; set; }
        public virtual DbSet<tbl_Login> tbl_Login { get; set; }
        public virtual DbSet<tbl_MedicalStaff> tbl_MedicalStaff { get; set; }
        public virtual DbSet<tbl_NextOfKin> tbl_NextOfKin { get; set; }
        public virtual DbSet<tbl_Patient> tbl_Patient { get; set; }
        public virtual DbSet<tbl_Staff_Patient> tbl_Staff_Patient { get; set; }
        public virtual DbSet<tbl_Student_Patient> tbl_Student_Patient { get; set; }
        public virtual DbSet<tbl_Visit> tbl_Visit { get; set; }
        public virtual DbSet<tbl_VitalSigns> tbl_VitalSigns { get; set; }
    
        public virtual ObjectResult<GET_tbl_Admin_Result> GET_tbl_Admin(Nullable<long> itbid, Nullable<int> taskid)
        {
            var itbidParameter = itbid.HasValue ?
                new ObjectParameter("itbid", itbid) :
                new ObjectParameter("itbid", typeof(long));
    
            var taskidParameter = taskid.HasValue ?
                new ObjectParameter("taskid", taskid) :
                new ObjectParameter("taskid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_tbl_Admin_Result>("GET_tbl_Admin", itbidParameter, taskidParameter);
        }
    
        public virtual ObjectResult<GET_tbl_Clinic_Result> GET_tbl_Clinic(Nullable<long> itbid, Nullable<int> taskid)
        {
            var itbidParameter = itbid.HasValue ?
                new ObjectParameter("itbid", itbid) :
                new ObjectParameter("itbid", typeof(long));
    
            var taskidParameter = taskid.HasValue ?
                new ObjectParameter("taskid", taskid) :
                new ObjectParameter("taskid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_tbl_Clinic_Result>("GET_tbl_Clinic", itbidParameter, taskidParameter);
        }
    
        public virtual ObjectResult<GET_tbl_ClinicOpenSchedule_Result> GET_tbl_ClinicOpenSchedule(Nullable<long> itbid, Nullable<int> taskid)
        {
            var itbidParameter = itbid.HasValue ?
                new ObjectParameter("itbid", itbid) :
                new ObjectParameter("itbid", typeof(long));
    
            var taskidParameter = taskid.HasValue ?
                new ObjectParameter("taskid", taskid) :
                new ObjectParameter("taskid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_tbl_ClinicOpenSchedule_Result>("GET_tbl_ClinicOpenSchedule", itbidParameter, taskidParameter);
        }
    
        public virtual ObjectResult<GET_tbl_Department_Result> GET_tbl_Department(Nullable<long> itbid, Nullable<int> taskid)
        {
            var itbidParameter = itbid.HasValue ?
                new ObjectParameter("itbid", itbid) :
                new ObjectParameter("itbid", typeof(long));
    
            var taskidParameter = taskid.HasValue ?
                new ObjectParameter("taskid", taskid) :
                new ObjectParameter("taskid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_tbl_Department_Result>("GET_tbl_Department", itbidParameter, taskidParameter);
        }
    
        public virtual ObjectResult<GET_tbl_Dependent_Result> GET_tbl_Dependent(Nullable<long> itbid, Nullable<int> taskid)
        {
            var itbidParameter = itbid.HasValue ?
                new ObjectParameter("itbid", itbid) :
                new ObjectParameter("itbid", typeof(long));
    
            var taskidParameter = taskid.HasValue ?
                new ObjectParameter("taskid", taskid) :
                new ObjectParameter("taskid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_tbl_Dependent_Result>("GET_tbl_Dependent", itbidParameter, taskidParameter);
        }
    
        public virtual ObjectResult<GET_tbl_Diagnosis_Result> GET_tbl_Diagnosis(Nullable<long> itbid, Nullable<int> taskid)
        {
            var itbidParameter = itbid.HasValue ?
                new ObjectParameter("itbid", itbid) :
                new ObjectParameter("itbid", typeof(long));
    
            var taskidParameter = taskid.HasValue ?
                new ObjectParameter("taskid", taskid) :
                new ObjectParameter("taskid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_tbl_Diagnosis_Result>("GET_tbl_Diagnosis", itbidParameter, taskidParameter);
        }
    
        public virtual ObjectResult<GET_tbl_Doctor_Result> GET_tbl_Doctor(Nullable<long> itbid, Nullable<int> taskid)
        {
            var itbidParameter = itbid.HasValue ?
                new ObjectParameter("itbid", itbid) :
                new ObjectParameter("itbid", typeof(long));
    
            var taskidParameter = taskid.HasValue ?
                new ObjectParameter("taskid", taskid) :
                new ObjectParameter("taskid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_tbl_Doctor_Result>("GET_tbl_Doctor", itbidParameter, taskidParameter);
        }
    
        public virtual ObjectResult<GET_tbl_Emergency_Result> GET_tbl_Emergency(Nullable<long> itbid, Nullable<int> taskid)
        {
            var itbidParameter = itbid.HasValue ?
                new ObjectParameter("itbid", itbid) :
                new ObjectParameter("itbid", typeof(long));
    
            var taskidParameter = taskid.HasValue ?
                new ObjectParameter("taskid", taskid) :
                new ObjectParameter("taskid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_tbl_Emergency_Result>("GET_tbl_Emergency", itbidParameter, taskidParameter);
        }
    
        public virtual ObjectResult<GET_tbl_Faculty_Result> GET_tbl_Faculty(Nullable<long> itbid, Nullable<int> taskid)
        {
            var itbidParameter = itbid.HasValue ?
                new ObjectParameter("itbid", itbid) :
                new ObjectParameter("itbid", typeof(long));
    
            var taskidParameter = taskid.HasValue ?
                new ObjectParameter("taskid", taskid) :
                new ObjectParameter("taskid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_tbl_Faculty_Result>("GET_tbl_Faculty", itbidParameter, taskidParameter);
        }
    
        public virtual ObjectResult<GET_tbl_Login_Result> GET_tbl_Login(Nullable<long> itbid, Nullable<int> taskid)
        {
            var itbidParameter = itbid.HasValue ?
                new ObjectParameter("itbid", itbid) :
                new ObjectParameter("itbid", typeof(long));
    
            var taskidParameter = taskid.HasValue ?
                new ObjectParameter("taskid", taskid) :
                new ObjectParameter("taskid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_tbl_Login_Result>("GET_tbl_Login", itbidParameter, taskidParameter);
        }
    
        public virtual ObjectResult<GET_tbl_MedicalStaff_Result> GET_tbl_MedicalStaff(Nullable<long> itbid, Nullable<int> taskid)
        {
            var itbidParameter = itbid.HasValue ?
                new ObjectParameter("itbid", itbid) :
                new ObjectParameter("itbid", typeof(long));
    
            var taskidParameter = taskid.HasValue ?
                new ObjectParameter("taskid", taskid) :
                new ObjectParameter("taskid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_tbl_MedicalStaff_Result>("GET_tbl_MedicalStaff", itbidParameter, taskidParameter);
        }
    
        public virtual ObjectResult<GET_tbl_NextOfKin_Result> GET_tbl_NextOfKin(Nullable<long> itbid, Nullable<int> taskid)
        {
            var itbidParameter = itbid.HasValue ?
                new ObjectParameter("itbid", itbid) :
                new ObjectParameter("itbid", typeof(long));
    
            var taskidParameter = taskid.HasValue ?
                new ObjectParameter("taskid", taskid) :
                new ObjectParameter("taskid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_tbl_NextOfKin_Result>("GET_tbl_NextOfKin", itbidParameter, taskidParameter);
        }
    
        public virtual ObjectResult<GET_tbl_Patient_Result> GET_tbl_Patient(Nullable<long> itbid, Nullable<int> taskid)
        {
            var itbidParameter = itbid.HasValue ?
                new ObjectParameter("itbid", itbid) :
                new ObjectParameter("itbid", typeof(long));
    
            var taskidParameter = taskid.HasValue ?
                new ObjectParameter("taskid", taskid) :
                new ObjectParameter("taskid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_tbl_Patient_Result>("GET_tbl_Patient", itbidParameter, taskidParameter);
        }
    
        public virtual ObjectResult<GET_tbl_Staff_Patient_Result> GET_tbl_Staff_Patient(Nullable<long> itbid, Nullable<int> taskid)
        {
            var itbidParameter = itbid.HasValue ?
                new ObjectParameter("itbid", itbid) :
                new ObjectParameter("itbid", typeof(long));
    
            var taskidParameter = taskid.HasValue ?
                new ObjectParameter("taskid", taskid) :
                new ObjectParameter("taskid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_tbl_Staff_Patient_Result>("GET_tbl_Staff_Patient", itbidParameter, taskidParameter);
        }
    
        public virtual ObjectResult<GET_tbl_Student_Patient_Result> GET_tbl_Student_Patient(Nullable<long> itbid, Nullable<int> taskid)
        {
            var itbidParameter = itbid.HasValue ?
                new ObjectParameter("itbid", itbid) :
                new ObjectParameter("itbid", typeof(long));
    
            var taskidParameter = taskid.HasValue ?
                new ObjectParameter("taskid", taskid) :
                new ObjectParameter("taskid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_tbl_Student_Patient_Result>("GET_tbl_Student_Patient", itbidParameter, taskidParameter);
        }
    
        public virtual ObjectResult<GET_tbl_Visit_Result> GET_tbl_Visit(Nullable<long> itbid, Nullable<int> taskid)
        {
            var itbidParameter = itbid.HasValue ?
                new ObjectParameter("itbid", itbid) :
                new ObjectParameter("itbid", typeof(long));
    
            var taskidParameter = taskid.HasValue ?
                new ObjectParameter("taskid", taskid) :
                new ObjectParameter("taskid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_tbl_Visit_Result>("GET_tbl_Visit", itbidParameter, taskidParameter);
        }
    
        public virtual ObjectResult<GET_tbl_VitalSigns_Result> GET_tbl_VitalSigns(Nullable<long> itbid, Nullable<int> taskid)
        {
            var itbidParameter = itbid.HasValue ?
                new ObjectParameter("itbid", itbid) :
                new ObjectParameter("itbid", typeof(long));
    
            var taskidParameter = taskid.HasValue ?
                new ObjectParameter("taskid", taskid) :
                new ObjectParameter("taskid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_tbl_VitalSigns_Result>("GET_tbl_VitalSigns", itbidParameter, taskidParameter);
        }
    
        public virtual int POST_tbl_Admin(Nullable<int> itbId, Nullable<int> medstaff_id, string status, string createdby, Nullable<System.DateTime> createDate, Nullable<int> taskid, ObjectParameter retVal, ObjectParameter retMsg)
        {
            var itbIdParameter = itbId.HasValue ?
                new ObjectParameter("ItbId", itbId) :
                new ObjectParameter("ItbId", typeof(int));
    
            var medstaff_idParameter = medstaff_id.HasValue ?
                new ObjectParameter("Medstaff_id", medstaff_id) :
                new ObjectParameter("Medstaff_id", typeof(int));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var createdbyParameter = createdby != null ?
                new ObjectParameter("Createdby", createdby) :
                new ObjectParameter("Createdby", typeof(string));
    
            var createDateParameter = createDate.HasValue ?
                new ObjectParameter("CreateDate", createDate) :
                new ObjectParameter("CreateDate", typeof(System.DateTime));
    
            var taskidParameter = taskid.HasValue ?
                new ObjectParameter("taskid", taskid) :
                new ObjectParameter("taskid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("POST_tbl_Admin", itbIdParameter, medstaff_idParameter, statusParameter, createdbyParameter, createDateParameter, taskidParameter, retVal, retMsg);
        }
    
        public virtual int POST_tbl_Clinic(Nullable<int> itbId, string clinic_name, string clinic_type, string clinic_description, Nullable<int> clinic_open_schedule, string status, string createdBy, Nullable<System.DateTime> createDate, Nullable<int> taskid, ObjectParameter retVal, ObjectParameter retMsg)
        {
            var itbIdParameter = itbId.HasValue ?
                new ObjectParameter("ItbId", itbId) :
                new ObjectParameter("ItbId", typeof(int));
    
            var clinic_nameParameter = clinic_name != null ?
                new ObjectParameter("Clinic_name", clinic_name) :
                new ObjectParameter("Clinic_name", typeof(string));
    
            var clinic_typeParameter = clinic_type != null ?
                new ObjectParameter("Clinic_type", clinic_type) :
                new ObjectParameter("Clinic_type", typeof(string));
    
            var clinic_descriptionParameter = clinic_description != null ?
                new ObjectParameter("Clinic_description", clinic_description) :
                new ObjectParameter("Clinic_description", typeof(string));
    
            var clinic_open_scheduleParameter = clinic_open_schedule.HasValue ?
                new ObjectParameter("clinic_open_schedule", clinic_open_schedule) :
                new ObjectParameter("clinic_open_schedule", typeof(int));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            var createDateParameter = createDate.HasValue ?
                new ObjectParameter("CreateDate", createDate) :
                new ObjectParameter("CreateDate", typeof(System.DateTime));
    
            var taskidParameter = taskid.HasValue ?
                new ObjectParameter("taskid", taskid) :
                new ObjectParameter("taskid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("POST_tbl_Clinic", itbIdParameter, clinic_nameParameter, clinic_typeParameter, clinic_descriptionParameter, clinic_open_scheduleParameter, statusParameter, createdByParameter, createDateParameter, taskidParameter, retVal, retMsg);
        }
    
        public virtual int POST_tbl_ClinicOpenSchedule(Nullable<int> itbId, string clinic_day, Nullable<System.TimeSpan> clinic_time, string status, string createdby, Nullable<System.DateTime> createDate, Nullable<int> taskid, ObjectParameter retVal, ObjectParameter retMsg)
        {
            var itbIdParameter = itbId.HasValue ?
                new ObjectParameter("ItbId", itbId) :
                new ObjectParameter("ItbId", typeof(int));
    
            var clinic_dayParameter = clinic_day != null ?
                new ObjectParameter("Clinic_day", clinic_day) :
                new ObjectParameter("Clinic_day", typeof(string));
    
            var clinic_timeParameter = clinic_time.HasValue ?
                new ObjectParameter("Clinic_time", clinic_time) :
                new ObjectParameter("Clinic_time", typeof(System.TimeSpan));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var createdbyParameter = createdby != null ?
                new ObjectParameter("Createdby", createdby) :
                new ObjectParameter("Createdby", typeof(string));
    
            var createDateParameter = createDate.HasValue ?
                new ObjectParameter("CreateDate", createDate) :
                new ObjectParameter("CreateDate", typeof(System.DateTime));
    
            var taskidParameter = taskid.HasValue ?
                new ObjectParameter("taskid", taskid) :
                new ObjectParameter("taskid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("POST_tbl_ClinicOpenSchedule", itbIdParameter, clinic_dayParameter, clinic_timeParameter, statusParameter, createdbyParameter, createDateParameter, taskidParameter, retVal, retMsg);
        }
    
        public virtual int POST_tbl_Department(Nullable<int> itbId, string department_title, string status, string createdby, Nullable<System.DateTime> createDate, Nullable<int> faculty_id, Nullable<int> taskid, ObjectParameter retVal, ObjectParameter retMsg)
        {
            var itbIdParameter = itbId.HasValue ?
                new ObjectParameter("ItbId", itbId) :
                new ObjectParameter("ItbId", typeof(int));
    
            var department_titleParameter = department_title != null ?
                new ObjectParameter("Department_title", department_title) :
                new ObjectParameter("Department_title", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var createdbyParameter = createdby != null ?
                new ObjectParameter("Createdby", createdby) :
                new ObjectParameter("Createdby", typeof(string));
    
            var createDateParameter = createDate.HasValue ?
                new ObjectParameter("CreateDate", createDate) :
                new ObjectParameter("CreateDate", typeof(System.DateTime));
    
            var faculty_idParameter = faculty_id.HasValue ?
                new ObjectParameter("Faculty_id", faculty_id) :
                new ObjectParameter("Faculty_id", typeof(int));
    
            var taskidParameter = taskid.HasValue ?
                new ObjectParameter("taskid", taskid) :
                new ObjectParameter("taskid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("POST_tbl_Department", itbIdParameter, department_titleParameter, statusParameter, createdbyParameter, createDateParameter, faculty_idParameter, taskidParameter, retVal, retMsg);
        }
    
        public virtual int POST_tbl_Dependent(Nullable<int> itbId, string relationship, Nullable<int> guardian_id, string status, string createdby, Nullable<System.DateTime> createDate, Nullable<int> taskid, ObjectParameter retVal, ObjectParameter retMsg)
        {
            var itbIdParameter = itbId.HasValue ?
                new ObjectParameter("ItbId", itbId) :
                new ObjectParameter("ItbId", typeof(int));
    
            var relationshipParameter = relationship != null ?
                new ObjectParameter("Relationship", relationship) :
                new ObjectParameter("Relationship", typeof(string));
    
            var guardian_idParameter = guardian_id.HasValue ?
                new ObjectParameter("Guardian_id", guardian_id) :
                new ObjectParameter("Guardian_id", typeof(int));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var createdbyParameter = createdby != null ?
                new ObjectParameter("Createdby", createdby) :
                new ObjectParameter("Createdby", typeof(string));
    
            var createDateParameter = createDate.HasValue ?
                new ObjectParameter("CreateDate", createDate) :
                new ObjectParameter("CreateDate", typeof(System.DateTime));
    
            var taskidParameter = taskid.HasValue ?
                new ObjectParameter("taskid", taskid) :
                new ObjectParameter("taskid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("POST_tbl_Dependent", itbIdParameter, relationshipParameter, guardian_idParameter, statusParameter, createdbyParameter, createDateParameter, taskidParameter, retVal, retMsg);
        }
    
        public virtual int POST_tbl_Diagnosis(Nullable<int> itbId, string diagnosis, string examination, string prescription, Nullable<int> visit_id, Nullable<int> vital_id, Nullable<int> doctor_id, string status, string createdBy, Nullable<System.DateTime> createDate, Nullable<int> taskid, ObjectParameter retVal, ObjectParameter retMsg)
        {
            var itbIdParameter = itbId.HasValue ?
                new ObjectParameter("ItbId", itbId) :
                new ObjectParameter("ItbId", typeof(int));
    
            var diagnosisParameter = diagnosis != null ?
                new ObjectParameter("Diagnosis", diagnosis) :
                new ObjectParameter("Diagnosis", typeof(string));
    
            var examinationParameter = examination != null ?
                new ObjectParameter("Examination", examination) :
                new ObjectParameter("Examination", typeof(string));
    
            var prescriptionParameter = prescription != null ?
                new ObjectParameter("Prescription", prescription) :
                new ObjectParameter("Prescription", typeof(string));
    
            var visit_idParameter = visit_id.HasValue ?
                new ObjectParameter("Visit_id", visit_id) :
                new ObjectParameter("Visit_id", typeof(int));
    
            var vital_idParameter = vital_id.HasValue ?
                new ObjectParameter("Vital_id", vital_id) :
                new ObjectParameter("Vital_id", typeof(int));
    
            var doctor_idParameter = doctor_id.HasValue ?
                new ObjectParameter("Doctor_id", doctor_id) :
                new ObjectParameter("Doctor_id", typeof(int));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            var createDateParameter = createDate.HasValue ?
                new ObjectParameter("CreateDate", createDate) :
                new ObjectParameter("CreateDate", typeof(System.DateTime));
    
            var taskidParameter = taskid.HasValue ?
                new ObjectParameter("taskid", taskid) :
                new ObjectParameter("taskid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("POST_tbl_Diagnosis", itbIdParameter, diagnosisParameter, examinationParameter, prescriptionParameter, visit_idParameter, vital_idParameter, doctor_idParameter, statusParameter, createdByParameter, createDateParameter, taskidParameter, retVal, retMsg);
        }
    
        public virtual int POST_tbl_Doctor(Nullable<int> itbId, string specialization, Nullable<int> staff_id, string status, string createdby, Nullable<System.DateTime> createDate, Nullable<int> taskid, ObjectParameter retVal, ObjectParameter retMsg)
        {
            var itbIdParameter = itbId.HasValue ?
                new ObjectParameter("ItbId", itbId) :
                new ObjectParameter("ItbId", typeof(int));
    
            var specializationParameter = specialization != null ?
                new ObjectParameter("Specialization", specialization) :
                new ObjectParameter("Specialization", typeof(string));
    
            var staff_idParameter = staff_id.HasValue ?
                new ObjectParameter("Staff_id", staff_id) :
                new ObjectParameter("Staff_id", typeof(int));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var createdbyParameter = createdby != null ?
                new ObjectParameter("Createdby", createdby) :
                new ObjectParameter("Createdby", typeof(string));
    
            var createDateParameter = createDate.HasValue ?
                new ObjectParameter("CreateDate", createDate) :
                new ObjectParameter("CreateDate", typeof(System.DateTime));
    
            var taskidParameter = taskid.HasValue ?
                new ObjectParameter("taskid", taskid) :
                new ObjectParameter("taskid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("POST_tbl_Doctor", itbIdParameter, specializationParameter, staff_idParameter, statusParameter, createdbyParameter, createDateParameter, taskidParameter, retVal, retMsg);
        }
    
        public virtual int POST_tbl_Emergency(Nullable<int> itbId, string emergency_case_number, Nullable<int> patient_id, string status, string createdby, Nullable<System.DateTime> createDate, Nullable<int> taskid, ObjectParameter retVal, ObjectParameter retMsg)
        {
            var itbIdParameter = itbId.HasValue ?
                new ObjectParameter("ItbId", itbId) :
                new ObjectParameter("ItbId", typeof(int));
    
            var emergency_case_numberParameter = emergency_case_number != null ?
                new ObjectParameter("Emergency_case_number", emergency_case_number) :
                new ObjectParameter("Emergency_case_number", typeof(string));
    
            var patient_idParameter = patient_id.HasValue ?
                new ObjectParameter("Patient_id", patient_id) :
                new ObjectParameter("Patient_id", typeof(int));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var createdbyParameter = createdby != null ?
                new ObjectParameter("Createdby", createdby) :
                new ObjectParameter("Createdby", typeof(string));
    
            var createDateParameter = createDate.HasValue ?
                new ObjectParameter("CreateDate", createDate) :
                new ObjectParameter("CreateDate", typeof(System.DateTime));
    
            var taskidParameter = taskid.HasValue ?
                new ObjectParameter("taskid", taskid) :
                new ObjectParameter("taskid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("POST_tbl_Emergency", itbIdParameter, emergency_case_numberParameter, patient_idParameter, statusParameter, createdbyParameter, createDateParameter, taskidParameter, retVal, retMsg);
        }
    
        public virtual int POST_tbl_Faculty(Nullable<int> itbId, string faculty_title, string status, string createdby, Nullable<System.DateTime> createDate, Nullable<int> taskid, ObjectParameter retVal, ObjectParameter retMsg)
        {
            var itbIdParameter = itbId.HasValue ?
                new ObjectParameter("ItbId", itbId) :
                new ObjectParameter("ItbId", typeof(int));
    
            var faculty_titleParameter = faculty_title != null ?
                new ObjectParameter("Faculty_title", faculty_title) :
                new ObjectParameter("Faculty_title", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var createdbyParameter = createdby != null ?
                new ObjectParameter("Createdby", createdby) :
                new ObjectParameter("Createdby", typeof(string));
    
            var createDateParameter = createDate.HasValue ?
                new ObjectParameter("CreateDate", createDate) :
                new ObjectParameter("CreateDate", typeof(System.DateTime));
    
            var taskidParameter = taskid.HasValue ?
                new ObjectParameter("taskid", taskid) :
                new ObjectParameter("taskid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("POST_tbl_Faculty", itbIdParameter, faculty_titleParameter, statusParameter, createdbyParameter, createDateParameter, taskidParameter, retVal, retMsg);
        }
    
        public virtual int POST_tbl_Login(Nullable<int> itbId, string username, string password, string user_type, Nullable<int> medical_staff, Nullable<int> userID, string status, string createdby, Nullable<System.DateTime> createDate, Nullable<int> taskid, ObjectParameter retVal, ObjectParameter retMsg)
        {
            var itbIdParameter = itbId.HasValue ?
                new ObjectParameter("ItbId", itbId) :
                new ObjectParameter("ItbId", typeof(int));
    
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var user_typeParameter = user_type != null ?
                new ObjectParameter("User_type", user_type) :
                new ObjectParameter("User_type", typeof(string));
    
            var medical_staffParameter = medical_staff.HasValue ?
                new ObjectParameter("Medical_staff", medical_staff) :
                new ObjectParameter("Medical_staff", typeof(int));
    
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            var createdbyParameter = createdby != null ?
                new ObjectParameter("Createdby", createdby) :
                new ObjectParameter("Createdby", typeof(string));
    
            var createDateParameter = createDate.HasValue ?
                new ObjectParameter("CreateDate", createDate) :
                new ObjectParameter("CreateDate", typeof(System.DateTime));
    
            var taskidParameter = taskid.HasValue ?
                new ObjectParameter("taskid", taskid) :
                new ObjectParameter("taskid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("POST_tbl_Login", itbIdParameter, usernameParameter, passwordParameter, user_typeParameter, medical_staffParameter, userIDParameter, statusParameter, createdbyParameter, createDateParameter, taskidParameter, retVal, retMsg);
        }
    
        public virtual int POST_tbl_MedicalStaff(Nullable<int> itbId, string staff_code, string first_name, string last_name, string other_name, string gender, string position, string phone_num, string address, string nationality, string staff_type, string role, string status, string createdby, Nullable<System.DateTime> createDate, Nullable<int> taskid, ObjectParameter retVal, ObjectParameter retMsg)
        {
            var itbIdParameter = itbId.HasValue ?
                new ObjectParameter("ItbId", itbId) :
                new ObjectParameter("ItbId", typeof(int));
    
            var staff_codeParameter = staff_code != null ?
                new ObjectParameter("Staff_code", staff_code) :
                new ObjectParameter("Staff_code", typeof(string));
    
            var first_nameParameter = first_name != null ?
                new ObjectParameter("First_name", first_name) :
                new ObjectParameter("First_name", typeof(string));
    
            var last_nameParameter = last_name != null ?
                new ObjectParameter("Last_name", last_name) :
                new ObjectParameter("Last_name", typeof(string));
    
            var other_nameParameter = other_name != null ?
                new ObjectParameter("Other_name", other_name) :
                new ObjectParameter("Other_name", typeof(string));
    
            var genderParameter = gender != null ?
                new ObjectParameter("Gender", gender) :
                new ObjectParameter("Gender", typeof(string));
    
            var positionParameter = position != null ?
                new ObjectParameter("Position", position) :
                new ObjectParameter("Position", typeof(string));
    
            var phone_numParameter = phone_num != null ?
                new ObjectParameter("Phone_num", phone_num) :
                new ObjectParameter("Phone_num", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("Address", address) :
                new ObjectParameter("Address", typeof(string));
    
            var nationalityParameter = nationality != null ?
                new ObjectParameter("Nationality", nationality) :
                new ObjectParameter("Nationality", typeof(string));
    
            var staff_typeParameter = staff_type != null ?
                new ObjectParameter("Staff_type", staff_type) :
                new ObjectParameter("Staff_type", typeof(string));
    
            var roleParameter = role != null ?
                new ObjectParameter("Role", role) :
                new ObjectParameter("Role", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var createdbyParameter = createdby != null ?
                new ObjectParameter("Createdby", createdby) :
                new ObjectParameter("Createdby", typeof(string));
    
            var createDateParameter = createDate.HasValue ?
                new ObjectParameter("CreateDate", createDate) :
                new ObjectParameter("CreateDate", typeof(System.DateTime));
    
            var taskidParameter = taskid.HasValue ?
                new ObjectParameter("taskid", taskid) :
                new ObjectParameter("taskid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("POST_tbl_MedicalStaff", itbIdParameter, staff_codeParameter, first_nameParameter, last_nameParameter, other_nameParameter, genderParameter, positionParameter, phone_numParameter, addressParameter, nationalityParameter, staff_typeParameter, roleParameter, statusParameter, createdbyParameter, createDateParameter, taskidParameter, retVal, retMsg);
        }
    
        public virtual int POST_tbl_NextOfKin(Nullable<int> itbId, string last_name, string first_name, string other_names, string phone_number, string gender, string address, string relationship, string status, string createdby, Nullable<System.DateTime> createDate, Nullable<int> taskid, ObjectParameter retVal, ObjectParameter retMsg)
        {
            var itbIdParameter = itbId.HasValue ?
                new ObjectParameter("ItbId", itbId) :
                new ObjectParameter("ItbId", typeof(int));
    
            var last_nameParameter = last_name != null ?
                new ObjectParameter("Last_name", last_name) :
                new ObjectParameter("Last_name", typeof(string));
    
            var first_nameParameter = first_name != null ?
                new ObjectParameter("First_name", first_name) :
                new ObjectParameter("First_name", typeof(string));
    
            var other_namesParameter = other_names != null ?
                new ObjectParameter("Other_names", other_names) :
                new ObjectParameter("Other_names", typeof(string));
    
            var phone_numberParameter = phone_number != null ?
                new ObjectParameter("Phone_number", phone_number) :
                new ObjectParameter("Phone_number", typeof(string));
    
            var genderParameter = gender != null ?
                new ObjectParameter("Gender", gender) :
                new ObjectParameter("Gender", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("Address", address) :
                new ObjectParameter("Address", typeof(string));
    
            var relationshipParameter = relationship != null ?
                new ObjectParameter("Relationship", relationship) :
                new ObjectParameter("Relationship", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var createdbyParameter = createdby != null ?
                new ObjectParameter("Createdby", createdby) :
                new ObjectParameter("Createdby", typeof(string));
    
            var createDateParameter = createDate.HasValue ?
                new ObjectParameter("CreateDate", createDate) :
                new ObjectParameter("CreateDate", typeof(System.DateTime));
    
            var taskidParameter = taskid.HasValue ?
                new ObjectParameter("taskid", taskid) :
                new ObjectParameter("taskid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("POST_tbl_NextOfKin", itbIdParameter, last_nameParameter, first_nameParameter, other_namesParameter, phone_numberParameter, genderParameter, addressParameter, relationshipParameter, statusParameter, createdbyParameter, createDateParameter, taskidParameter, retVal, retMsg);
        }
    
        public virtual int POST_tbl_Patient(Nullable<int> itbId, string last_name, string first_name, string other_names, string phone_number, string gender, string hospital_number, Nullable<System.DateTime> date_of_birth, string address, string marital_status, string nationality, string patient_type, Nullable<int> next_of_kin, Nullable<int> department, Nullable<int> dependent_id, string status, string createdBy, Nullable<System.DateTime> createDate, Nullable<int> taskid, ObjectParameter retVal, ObjectParameter retMsg)
        {
            var itbIdParameter = itbId.HasValue ?
                new ObjectParameter("ItbId", itbId) :
                new ObjectParameter("ItbId", typeof(int));
    
            var last_nameParameter = last_name != null ?
                new ObjectParameter("Last_name", last_name) :
                new ObjectParameter("Last_name", typeof(string));
    
            var first_nameParameter = first_name != null ?
                new ObjectParameter("First_name", first_name) :
                new ObjectParameter("First_name", typeof(string));
    
            var other_namesParameter = other_names != null ?
                new ObjectParameter("Other_names", other_names) :
                new ObjectParameter("Other_names", typeof(string));
    
            var phone_numberParameter = phone_number != null ?
                new ObjectParameter("Phone_number", phone_number) :
                new ObjectParameter("Phone_number", typeof(string));
    
            var genderParameter = gender != null ?
                new ObjectParameter("Gender", gender) :
                new ObjectParameter("Gender", typeof(string));
    
            var hospital_numberParameter = hospital_number != null ?
                new ObjectParameter("Hospital_number", hospital_number) :
                new ObjectParameter("Hospital_number", typeof(string));
    
            var date_of_birthParameter = date_of_birth.HasValue ?
                new ObjectParameter("Date_of_birth", date_of_birth) :
                new ObjectParameter("Date_of_birth", typeof(System.DateTime));
    
            var addressParameter = address != null ?
                new ObjectParameter("Address", address) :
                new ObjectParameter("Address", typeof(string));
    
            var marital_statusParameter = marital_status != null ?
                new ObjectParameter("Marital_status", marital_status) :
                new ObjectParameter("Marital_status", typeof(string));
    
            var nationalityParameter = nationality != null ?
                new ObjectParameter("Nationality", nationality) :
                new ObjectParameter("Nationality", typeof(string));
    
            var patient_typeParameter = patient_type != null ?
                new ObjectParameter("Patient_type", patient_type) :
                new ObjectParameter("Patient_type", typeof(string));
    
            var next_of_kinParameter = next_of_kin.HasValue ?
                new ObjectParameter("Next_of_kin", next_of_kin) :
                new ObjectParameter("Next_of_kin", typeof(int));
    
            var departmentParameter = department.HasValue ?
                new ObjectParameter("Department", department) :
                new ObjectParameter("Department", typeof(int));
    
            var dependent_idParameter = dependent_id.HasValue ?
                new ObjectParameter("Dependent_id", dependent_id) :
                new ObjectParameter("Dependent_id", typeof(int));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            var createDateParameter = createDate.HasValue ?
                new ObjectParameter("CreateDate", createDate) :
                new ObjectParameter("CreateDate", typeof(System.DateTime));
    
            var taskidParameter = taskid.HasValue ?
                new ObjectParameter("taskid", taskid) :
                new ObjectParameter("taskid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("POST_tbl_Patient", itbIdParameter, last_nameParameter, first_nameParameter, other_namesParameter, phone_numberParameter, genderParameter, hospital_numberParameter, date_of_birthParameter, addressParameter, marital_statusParameter, nationalityParameter, patient_typeParameter, next_of_kinParameter, departmentParameter, dependent_idParameter, statusParameter, createdByParameter, createDateParameter, taskidParameter, retVal, retMsg);
        }
    
        public virtual int POST_tbl_Staff_Patient(Nullable<int> itbId, string staff_code, Nullable<int> no_of_dependent, Nullable<int> date_of_employment, Nullable<int> patient_id, string status, string createdby, Nullable<System.DateTime> createDate, Nullable<int> taskid, ObjectParameter retVal, ObjectParameter retMsg)
        {
            var itbIdParameter = itbId.HasValue ?
                new ObjectParameter("ItbId", itbId) :
                new ObjectParameter("ItbId", typeof(int));
    
            var staff_codeParameter = staff_code != null ?
                new ObjectParameter("Staff_code", staff_code) :
                new ObjectParameter("Staff_code", typeof(string));
    
            var no_of_dependentParameter = no_of_dependent.HasValue ?
                new ObjectParameter("No_of_dependent", no_of_dependent) :
                new ObjectParameter("No_of_dependent", typeof(int));
    
            var date_of_employmentParameter = date_of_employment.HasValue ?
                new ObjectParameter("Date_of_employment", date_of_employment) :
                new ObjectParameter("Date_of_employment", typeof(int));
    
            var patient_idParameter = patient_id.HasValue ?
                new ObjectParameter("Patient_id", patient_id) :
                new ObjectParameter("Patient_id", typeof(int));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var createdbyParameter = createdby != null ?
                new ObjectParameter("Createdby", createdby) :
                new ObjectParameter("Createdby", typeof(string));
    
            var createDateParameter = createDate.HasValue ?
                new ObjectParameter("CreateDate", createDate) :
                new ObjectParameter("CreateDate", typeof(System.DateTime));
    
            var taskidParameter = taskid.HasValue ?
                new ObjectParameter("taskid", taskid) :
                new ObjectParameter("taskid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("POST_tbl_Staff_Patient", itbIdParameter, staff_codeParameter, no_of_dependentParameter, date_of_employmentParameter, patient_idParameter, statusParameter, createdbyParameter, createDateParameter, taskidParameter, retVal, retMsg);
        }
    
        public virtual int POST_tbl_Student_Patient(Nullable<int> itbId, string matric_number, Nullable<System.DateTime> year_of_admission, Nullable<int> patient_id, string status, string createdby, Nullable<System.DateTime> createDate, Nullable<int> taskid, ObjectParameter retVal, ObjectParameter retMsg)
        {
            var itbIdParameter = itbId.HasValue ?
                new ObjectParameter("ItbId", itbId) :
                new ObjectParameter("ItbId", typeof(int));
    
            var matric_numberParameter = matric_number != null ?
                new ObjectParameter("Matric_number", matric_number) :
                new ObjectParameter("Matric_number", typeof(string));
    
            var year_of_admissionParameter = year_of_admission.HasValue ?
                new ObjectParameter("Year_of_admission", year_of_admission) :
                new ObjectParameter("Year_of_admission", typeof(System.DateTime));
    
            var patient_idParameter = patient_id.HasValue ?
                new ObjectParameter("Patient_id", patient_id) :
                new ObjectParameter("Patient_id", typeof(int));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var createdbyParameter = createdby != null ?
                new ObjectParameter("Createdby", createdby) :
                new ObjectParameter("Createdby", typeof(string));
    
            var createDateParameter = createDate.HasValue ?
                new ObjectParameter("CreateDate", createDate) :
                new ObjectParameter("CreateDate", typeof(System.DateTime));
    
            var taskidParameter = taskid.HasValue ?
                new ObjectParameter("taskid", taskid) :
                new ObjectParameter("taskid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("POST_tbl_Student_Patient", itbIdParameter, matric_numberParameter, year_of_admissionParameter, patient_idParameter, statusParameter, createdbyParameter, createDateParameter, taskidParameter, retVal, retMsg);
        }
    
        public virtual int POST_tbl_Visit(Nullable<int> itbId, Nullable<System.DateTime> visit_datetime, Nullable<int> patient_id, Nullable<int> recordstaff_id, Nullable<int> clinic_id, string status, string createdBy, Nullable<System.DateTime> createDate, Nullable<int> taskid, ObjectParameter retVal, ObjectParameter retMsg)
        {
            var itbIdParameter = itbId.HasValue ?
                new ObjectParameter("ItbId", itbId) :
                new ObjectParameter("ItbId", typeof(int));
    
            var visit_datetimeParameter = visit_datetime.HasValue ?
                new ObjectParameter("Visit_datetime", visit_datetime) :
                new ObjectParameter("Visit_datetime", typeof(System.DateTime));
    
            var patient_idParameter = patient_id.HasValue ?
                new ObjectParameter("Patient_id", patient_id) :
                new ObjectParameter("Patient_id", typeof(int));
    
            var recordstaff_idParameter = recordstaff_id.HasValue ?
                new ObjectParameter("Recordstaff_id", recordstaff_id) :
                new ObjectParameter("Recordstaff_id", typeof(int));
    
            var clinic_idParameter = clinic_id.HasValue ?
                new ObjectParameter("Clinic_id", clinic_id) :
                new ObjectParameter("Clinic_id", typeof(int));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            var createDateParameter = createDate.HasValue ?
                new ObjectParameter("CreateDate", createDate) :
                new ObjectParameter("CreateDate", typeof(System.DateTime));
    
            var taskidParameter = taskid.HasValue ?
                new ObjectParameter("taskid", taskid) :
                new ObjectParameter("taskid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("POST_tbl_Visit", itbIdParameter, visit_datetimeParameter, patient_idParameter, recordstaff_idParameter, clinic_idParameter, statusParameter, createdByParameter, createDateParameter, taskidParameter, retVal, retMsg);
        }
    
        public virtual int POST_tbl_VitalSigns(Nullable<int> itbId, string blood_pressure, string temperature, Nullable<decimal> pulse, string respiratory, Nullable<int> visit_id, Nullable<int> nurse_id, string status, string createdBy, Nullable<System.DateTime> createDate, Nullable<int> taskid, ObjectParameter retVal, ObjectParameter retMsg)
        {
            var itbIdParameter = itbId.HasValue ?
                new ObjectParameter("ItbId", itbId) :
                new ObjectParameter("ItbId", typeof(int));
    
            var blood_pressureParameter = blood_pressure != null ?
                new ObjectParameter("Blood_pressure", blood_pressure) :
                new ObjectParameter("Blood_pressure", typeof(string));
    
            var temperatureParameter = temperature != null ?
                new ObjectParameter("Temperature", temperature) :
                new ObjectParameter("Temperature", typeof(string));
    
            var pulseParameter = pulse.HasValue ?
                new ObjectParameter("Pulse", pulse) :
                new ObjectParameter("Pulse", typeof(decimal));
    
            var respiratoryParameter = respiratory != null ?
                new ObjectParameter("Respiratory", respiratory) :
                new ObjectParameter("Respiratory", typeof(string));
    
            var visit_idParameter = visit_id.HasValue ?
                new ObjectParameter("Visit_id", visit_id) :
                new ObjectParameter("Visit_id", typeof(int));
    
            var nurse_idParameter = nurse_id.HasValue ?
                new ObjectParameter("Nurse_id", nurse_id) :
                new ObjectParameter("Nurse_id", typeof(int));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            var createDateParameter = createDate.HasValue ?
                new ObjectParameter("CreateDate", createDate) :
                new ObjectParameter("CreateDate", typeof(System.DateTime));
    
            var taskidParameter = taskid.HasValue ?
                new ObjectParameter("taskid", taskid) :
                new ObjectParameter("taskid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("POST_tbl_VitalSigns", itbIdParameter, blood_pressureParameter, temperatureParameter, pulseParameter, respiratoryParameter, visit_idParameter, nurse_idParameter, statusParameter, createdByParameter, createDateParameter, taskidParameter, retVal, retMsg);
        }
    }
}
